name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: craftech-io/slack-action@v1
      with:
          status: starting
          channel: '#testing-for-punnet'
          if: always()
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      id: checkout
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        id: npm 
    - run: npm install
  #  - run: npm run build --if-present
   # - run: npm test
      env:
        CI: true
    - uses: craftech-io/slack-action@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() 
