name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#testing-for-punnet'
        if: always()
    - name: checkout
      id: var
    - uses: actions/checkout@v2
    - name: varible
      id: action
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build image
      id: NPM install
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
